import { Injectable } from '@angular/core';
import { ISchoolYear } from 'src/app/core/Models';

@Injectable({
  providedIn: 'root'
})
export class SchoolYearsService {

  cities: string[];
  schoolYearList:ISchoolYear[]=[];
  constructor() {

    this.schoolYearList = [
      { 'id': 1, 'class':'Third class','weekendDays':['Monday','Friday'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '(815) 6180492', 'schoolYearEndDate': '30/09/2021', 'curriculum': 'Female', 'schoolYearName': 'Somalia','ageDeterminationDate':'','annualHolidayName':'', 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':'' },
      { 'id': 2, 'class':'Third class','weekendDays':['Monday','Friday'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '(507) 3119958', 'schoolYearEndDate': '30/09/2021', 'curriculum': 'Male', 'schoolYearName': 'United States','ageDeterminationDate':'' ,'annualHolidayName':'', 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':'' },
      { 'id': 3, 'class':'Third class','weekendDays':['Monday','Friday'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '(478) 7181722', 'schoolYearEndDate': '30/09/2021', 'curriculum': 'Female', 'schoolYearName': 'Russia','ageDeterminationDate':'' ,'annualHolidayName':'' , 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':'' },
      { 'id': 4, 'class':'Third class','weekendDays':['Monday','Friday'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '(698) 4411762', 'schoolYearEndDate': '30/09/2021', 'curriculum': 'Female', 'schoolYearName': 'China','ageDeterminationDate':'' ,'annualHolidayName':'' , 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':'' },
      { 'id': 5, 'class':'Third class','weekendDays':['Monday','Friday'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '(345) 6582965', 'schoolYearEndDate': '30/09/2021', 'curriculum': 'Male', 'schoolYearName': 'Mongolia','ageDeterminationDate':'' ,'annualHolidayName':'' , 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':'' },
      { 'id': 6, 'class':'Third class','weekendDays':['Monday','Friday'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '(659) 9557733', 'schoolYearEndDate': '30/09/2021', 'curriculum': 'Male', 'schoolYearName': 'Bhutan','ageDeterminationDate':'' ,'annualHolidayName':'' , 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':'' },
      { 'id': 7, 'class':'Third class','weekendDays':['Monday','Friday'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '(864) 2101861', 'schoolYearEndDate': '30/09/2021', 'curriculum': 'Male', 'schoolYearName': 'Peru','ageDeterminationDate':'' ,'annualHolidayName':'', 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':''  },
      { 'id': 8,'class':'Third class','weekendDays':['Monday','Friday'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '(165) 5814372', 'schoolYearEndDate': '30/09/2021', 'curriculum': 'Male', 'schoolYearName': 'Niger','ageDeterminationDate':'' ,'annualHolidayName':'', 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':''  },
      { 'id': 9, 'class':'Third class','weekendDays':['Monday','Friday'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '(428) 2282928', 'schoolYearEndDate': '30/09/2021', 'curriculum': 'Female', 'schoolYearName': 'Argentina','ageDeterminationDate':'' ,'annualHolidayName':'' , 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':'' },
      { 'id': 10, 'class':'Third class','weekendDays':['Monday','Friday'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '(673) 5170425', 'schoolYearEndDate': '30/09/2021', 'curriculum': 'Female', 'schoolYearName': 'Greece','ageDeterminationDate':'' ,'annualHolidayName':'', 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':''  },
      { 'id': 11, 'class':'Third class','weekendDays':['Monday','Friday'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '(978) 8885907', 'schoolYearEndDate': '30/09/2021', 'curriculum': 'Female', 'schoolYearName': 'Indonesia','ageDeterminationDate':'' ,'annualHolidayName':'' , 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':'' },
      { 'id': 12, 'class':'Third class','weekendDays':['Monday','Friday'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '(956) 9360112', 'schoolYearEndDate': '30/09/2021', 'curriculum': 'Female', 'schoolYearName': 'Finland','ageDeterminationDate':'' ,'annualHolidayName':'', 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':''  },
      { 'id': 13, 'class':'Third class','weekendDays':['Monday','Friday'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '(240) 7150720', 'schoolYearEndDate': '30/09/2021', 'curriculum': 'Female', 'schoolYearName': 'Philippines' ,'ageDeterminationDate':'' ,'annualHolidayName':'', 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':'' },
      { 'id': 14, 'class':'Third class','weekendDays':['Monday','Friday'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '(416) 4076124', 'schoolYearEndDate': '30/09/2021', 'curriculum': 'Male', 'schoolYearName': 'Bosnia and Herzegovina','ageDeterminationDate':'' ,'annualHolidayName':'' , 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':'' },
      { 'id': 15, 'class':'Third class','weekendDays':['Monday','Friday'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '(262) 7945277', 'schoolYearEndDate': '30/09/2021', 'curriculum': 'Female', 'schoolYearName': 'Bolivia','ageDeterminationDate':'' ,'annualHolidayName':'' , 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':'' },
      { 'id': 16, 'class':'Third class','weekendDays':['Monday','Friday'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '(501) 3984600', 'schoolYearEndDate': '30/09/2021', 'curriculum': 'Female', 'schoolYearName': 'China','ageDeterminationDate':'' ,'annualHolidayName':'', 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':''  },
      { 'id': 17, 'class':'Third class','weekendDays':['Monday','Friday'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '(718) 4157883', 'schoolYearEndDate': '30/09/2021', 'curriculum': 'Male', 'schoolYearName': 'Finland','ageDeterminationDate':'' ,'annualHolidayName':'' , 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':'' },
      { 'id': 18, 'class':'Third class','weekendDays':['Monday','Friday'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '(213) 5730967', 'schoolYearEndDate': '30/09/2021', 'curriculum': 'Male', 'schoolYearName': 'Portugal','ageDeterminationDate':'' ,'annualHolidayName':'' , 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':'' },
      { 'id': 19, 'class':'Third class','weekendDays':['Monday','Friday'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '(349) 6453938', 'schoolYearEndDate': '30/09/2021', 'curriculum': 'Female', 'schoolYearName': 'Madagascar','ageDeterminationDate':'' ,'annualHolidayName':'', 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':''  },
      { 'id': 20,'class':'Third class','weekendDays':['Monday','Friday'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '(474) 3068249', 'schoolYearEndDate': '30/09/2021', 'curriculum': 'Female', 'schoolYearName': 'Greece','ageDeterminationDate':'' ,'annualHolidayName':'' , 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':'' }
    ];
    this.cities = [
      "2022",
       "Rome",
       "London",
       "Istanbul",
       "Paris"
  ];
   }
}
