import { Injectable } from '@angular/core';
import { ISchoolYear } from 'src/app/core/Models/school-years/school-year';

@Injectable({
  providedIn: 'root'
})
export class SchoolYearsService {

  cities: string[];
  schoolYearList:ISchoolYear[]=[];
  constructor() {

    this.schoolYearList = [
      { 'id': 1, 'class':'1','weekendDays':['السبت',' الأحد'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '2021/02/24', 'schoolYearEndDate': '30/09/2021', 'curriculum': '1', 'schoolYearName': '2022 - 2021','ageDeterminationDate':'','annualHolidayName':'', 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':'' },
      { 'id': 2, 'class':'1','weekendDays':['السبت',' الأحد'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '2021/02/24', 'schoolYearEndDate': '30/09/2021', 'curriculum': '1', 'schoolYearName': '2022 - 2021','ageDeterminationDate':'' ,'annualHolidayName':'', 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':'' },
      { 'id': 3, 'class':'1','weekendDays':['السبت',' الأحد'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '2021/02/24', 'schoolYearEndDate': '30/09/2021', 'curriculum': '1', 'schoolYearName': '2022 - 2021','ageDeterminationDate':'' ,'annualHolidayName':'' , 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':'' },
      { 'id': 4, 'class':'1','weekendDays':['السبت',' الأحد'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '2021/02/24', 'schoolYearEndDate': '30/09/2021', 'curriculum': '1', 'schoolYearName': '2022 - 2021','ageDeterminationDate':'' ,'annualHolidayName':'' , 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':'' },
      { 'id': 5, 'class':'1','weekendDays':['السبت',' الأحد'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '2021/02/24', 'schoolYearEndDate': '30/09/2021', 'curriculum': '1', 'schoolYearName': '2022 - 2021','ageDeterminationDate':'' ,'annualHolidayName':'' , 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':'' },
      { 'id': 6, 'class':'1','weekendDays':['السبت',' الأحد'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '2021/02/24', 'schoolYearEndDate': '30/09/2021', 'curriculum': '1', 'schoolYearName': '2022 - 2021','ageDeterminationDate':'' ,'annualHolidayName':'' , 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':'' },
      { 'id': 7, 'class':'1','weekendDays':['السبت',' الأحد'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '2021/02/24', 'schoolYearEndDate': '30/09/2021', 'curriculum': '1', 'schoolYearName': '2022 - 2021','ageDeterminationDate':'' ,'annualHolidayName':'', 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':''  },
      { 'id': 8,'class':'1','weekendDays':['السبت',' الأحد'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '2021/02/24', 'schoolYearEndDate': '30/09/2021', 'curriculum': '1', 'schoolYearName': '2022 - 2021','ageDeterminationDate':'' ,'annualHolidayName':'', 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':''  },
      { 'id': 9, 'class':'1','weekendDays':['السبت',' الأحد'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '2021/02/24', 'schoolYearEndDate': '30/09/2021', 'curriculum': '1', 'schoolYearName': '2022 - 2021','ageDeterminationDate':'' ,'annualHolidayName':'' , 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':'' },
      { 'id': 10, 'class':'1','weekendDays':['السبت',' الأحد'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '2021/02/24', 'schoolYearEndDate': '30/09/2021', 'curriculum': '1', 'schoolYearName': '2022 - 2021','ageDeterminationDate':'' ,'annualHolidayName':'', 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':''  },
      { 'id': 11, 'class':'1','weekendDays':['السبت',' الأحد'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '2021/02/24', 'schoolYearEndDate': '30/09/2021', 'curriculum': '1', 'schoolYearName': '2022 - 2021','ageDeterminationDate':'' ,'annualHolidayName':'' , 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':'' },
      { 'id': 12, 'class':'1','weekendDays':['السبت',' الأحد'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '2021/02/24', 'schoolYearEndDate': '30/09/2021', 'curriculum': '1', 'schoolYearName': '2022 - 2021','ageDeterminationDate':'' ,'annualHolidayName':'', 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':''  },
      { 'id': 13, 'class':'1','weekendDays':['السبت',' الأحد'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '2021/02/24', 'schoolYearEndDate': '30/09/2021', 'curriculum': '1', 'schoolYearName': '2022 - 2021' ,'ageDeterminationDate':'' ,'annualHolidayName':'', 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':'' },
      { 'id': 14, 'class':'1','weekendDays':['السبت',' الأحد'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '2021/02/24', 'schoolYearEndDate': '30/09/2021', 'curriculum': '1', 'schoolYearName': '2022 - 2021','ageDeterminationDate':'' ,'annualHolidayName':'' , 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':'' },
      { 'id': 15, 'class':'1','weekendDays':['السبت',' الأحد'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '2021/02/24', 'schoolYearEndDate': '30/09/2021', 'curriculum': '1', 'schoolYearName': '2022 - 2021','ageDeterminationDate':'' ,'annualHolidayName':'' , 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':'' },
      { 'id': 16, 'class':'1','weekendDays':['السبت',' الأحد'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '(2021/02/24', 'schoolYearEndDate': '30/09/2021', 'curriculum': '1', 'schoolYearName': '2022 - 2021','ageDeterminationDate':'' ,'annualHolidayName':'', 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':''  },
      { 'id': 17, 'class':'1','weekendDays':['السبت',' الأحد'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '2021/02/24', 'schoolYearEndDate': '30/09/2021', 'curriculum': '1', 'schoolYearName': '2022 - 2021','ageDeterminationDate':'' ,'annualHolidayName':'' , 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':'' },
      { 'id': 18, 'class':'1','weekendDays':['السبت',' الأحد'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '2021/02/24', 'schoolYearEndDate': '30/09/2021', 'curriculum': '1', 'schoolYearName': '2022 - 2021','ageDeterminationDate':'' ,'annualHolidayName':'' , 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':'' },
      { 'id': 19, 'class':'1','weekendDays':['السبت',' الأحد'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '2021/02/24', 'schoolYearEndDate': '30/09/2021', 'curriculum': '1', 'schoolYearName': '2022 - 2021','ageDeterminationDate':'' ,'annualHolidayName':'', 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':''  },
      { 'id': 20,'class':'1','weekendDays':['السبت',' الأحد'],'schoolYearStartDate':'24/02/2021' , 'createdDate': '2021/02/24', 'schoolYearEndDate': '30/09/2021', 'curriculum': '1', 'schoolYearName': '2022 - 2021','ageDeterminationDate':'' ,'annualHolidayName':'' , 'knownSubjectList':'','subjectStatus':'','subjectStatusInFinalTotal':'','activateAge':'','ageRequirementToRegisterFromInsideCountry':'','ageRequirementToRegisterFromOutsideCountry':'' }
    ];
    this.cities = [
      "2022",
       "Rome",
       "London",
       "Istanbul",
       "Paris"
  ];
   }
}
