import { Injectable } from '@angular/core';
import { ischoolyear } from 'src/app/core/Models';

@Injectable({
  providedIn: 'root'
})
export class SchoolYearsService {

  cities: string[];
  schoolyearlist:ischoolyear[]=[];
  constructor() {

    this.schoolyearlist = [
      { 'id': 1, 'class':'Third class','weekenddays':['Monday','Friday'],'schoolyearstartdate':'24/02/2021' , 'createddate': '(815) 6180492', 'schoolyearenddate': '30/09/2021', 'curriculum': 'Female', 'schoolyearname': 'Somalia','agedeterminationdate':'','annualholidayname':'', 'knownsubjectlist':'','subjectstatus':'','subjectstatusinfinaltotal':'','activateage':'','agerequirementtoregisterfrominsidecountry':'','agerequirementtoregisterfromoutsidecountry':'' },
      { 'id': 2, 'class':'Third class','weekenddays':['Monday','Friday'],'schoolyearstartdate':'24/02/2021' , 'createddate': '(507) 3119958', 'schoolyearenddate': '30/09/2021', 'curriculum': 'Male', 'schoolyearname': 'United States','agedeterminationdate':'' ,'annualholidayname':'', 'knownsubjectlist':'','subjectstatus':'','subjectstatusinfinaltotal':'','activateage':'','agerequirementtoregisterfrominsidecountry':'','agerequirementtoregisterfromoutsidecountry':'' },
      { 'id': 3, 'class':'Third class','weekenddays':['Monday','Friday'],'schoolyearstartdate':'24/02/2021' , 'createddate': '(478) 7181722', 'schoolyearenddate': '30/09/2021', 'curriculum': 'Female', 'schoolyearname': 'Russia','agedeterminationdate':'' ,'annualholidayname':'' , 'knownsubjectlist':'','subjectstatus':'','subjectstatusinfinaltotal':'','activateage':'','agerequirementtoregisterfrominsidecountry':'','agerequirementtoregisterfromoutsidecountry':'' },
      { 'id': 4, 'class':'Third class','weekenddays':['Monday','Friday'],'schoolyearstartdate':'24/02/2021' , 'createddate': '(698) 4411762', 'schoolyearenddate': '30/09/2021', 'curriculum': 'Female', 'schoolyearname': 'China','agedeterminationdate':'' ,'annualholidayname':'' , 'knownsubjectlist':'','subjectstatus':'','subjectstatusinfinaltotal':'','activateage':'','agerequirementtoregisterfrominsidecountry':'','agerequirementtoregisterfromoutsidecountry':'' },
      { 'id': 5, 'class':'Third class','weekenddays':['Monday','Friday'],'schoolyearstartdate':'24/02/2021' , 'createddate': '(345) 6582965', 'schoolyearenddate': '30/09/2021', 'curriculum': 'Male', 'schoolyearname': 'Mongolia','agedeterminationdate':'' ,'annualholidayname':'' , 'knownsubjectlist':'','subjectstatus':'','subjectstatusinfinaltotal':'','activateage':'','agerequirementtoregisterfrominsidecountry':'','agerequirementtoregisterfromoutsidecountry':'' },
      { 'id': 6, 'class':'Third class','weekenddays':['Monday','Friday'],'schoolyearstartdate':'24/02/2021' , 'createddate': '(659) 9557733', 'schoolyearenddate': '30/09/2021', 'curriculum': 'Male', 'schoolyearname': 'Bhutan','agedeterminationdate':'' ,'annualholidayname':'' , 'knownsubjectlist':'','subjectstatus':'','subjectstatusinfinaltotal':'','activateage':'','agerequirementtoregisterfrominsidecountry':'','agerequirementtoregisterfromoutsidecountry':'' },
      { 'id': 7, 'class':'Third class','weekenddays':['Monday','Friday'],'schoolyearstartdate':'24/02/2021' , 'createddate': '(864) 2101861', 'schoolyearenddate': '30/09/2021', 'curriculum': 'Male', 'schoolyearname': 'Peru','agedeterminationdate':'' ,'annualholidayname':'', 'knownsubjectlist':'','subjectstatus':'','subjectstatusinfinaltotal':'','activateage':'','agerequirementtoregisterfrominsidecountry':'','agerequirementtoregisterfromoutsidecountry':''  },
      { 'id': 8,'class':'Third class','weekenddays':['Monday','Friday'],'schoolyearstartdate':'24/02/2021' , 'createddate': '(165) 5814372', 'schoolyearenddate': '30/09/2021', 'curriculum': 'Male', 'schoolyearname': 'Niger','agedeterminationdate':'' ,'annualholidayname':'', 'knownsubjectlist':'','subjectstatus':'','subjectstatusinfinaltotal':'','activateage':'','agerequirementtoregisterfrominsidecountry':'','agerequirementtoregisterfromoutsidecountry':''  },
      { 'id': 9, 'class':'Third class','weekenddays':['Monday','Friday'],'schoolyearstartdate':'24/02/2021' , 'createddate': '(428) 2282928', 'schoolyearenddate': '30/09/2021', 'curriculum': 'Female', 'schoolyearname': 'Argentina','agedeterminationdate':'' ,'annualholidayname':'' , 'knownsubjectlist':'','subjectstatus':'','subjectstatusinfinaltotal':'','activateage':'','agerequirementtoregisterfrominsidecountry':'','agerequirementtoregisterfromoutsidecountry':'' },
      { 'id': 10, 'class':'Third class','weekenddays':['Monday','Friday'],'schoolyearstartdate':'24/02/2021' , 'createddate': '(673) 5170425', 'schoolyearenddate': '30/09/2021', 'curriculum': 'Female', 'schoolyearname': 'Greece','agedeterminationdate':'' ,'annualholidayname':'', 'knownsubjectlist':'','subjectstatus':'','subjectstatusinfinaltotal':'','activateage':'','agerequirementtoregisterfrominsidecountry':'','agerequirementtoregisterfromoutsidecountry':''  },
      { 'id': 11, 'class':'Third class','weekenddays':['Monday','Friday'],'schoolyearstartdate':'24/02/2021' , 'createddate': '(978) 8885907', 'schoolyearenddate': '30/09/2021', 'curriculum': 'Female', 'schoolyearname': 'Indonesia','agedeterminationdate':'' ,'annualholidayname':'' , 'knownsubjectlist':'','subjectstatus':'','subjectstatusinfinaltotal':'','activateage':'','agerequirementtoregisterfrominsidecountry':'','agerequirementtoregisterfromoutsidecountry':'' },
      { 'id': 12, 'class':'Third class','weekenddays':['Monday','Friday'],'schoolyearstartdate':'24/02/2021' , 'createddate': '(956) 9360112', 'schoolyearenddate': '30/09/2021', 'curriculum': 'Female', 'schoolyearname': 'Finland','agedeterminationdate':'' ,'annualholidayname':'', 'knownsubjectlist':'','subjectstatus':'','subjectstatusinfinaltotal':'','activateage':'','agerequirementtoregisterfrominsidecountry':'','agerequirementtoregisterfromoutsidecountry':''  },
      { 'id': 13, 'class':'Third class','weekenddays':['Monday','Friday'],'schoolyearstartdate':'24/02/2021' , 'createddate': '(240) 7150720', 'schoolyearenddate': '30/09/2021', 'curriculum': 'Female', 'schoolyearname': 'Philippines' ,'agedeterminationdate':'' ,'annualholidayname':'', 'knownsubjectlist':'','subjectstatus':'','subjectstatusinfinaltotal':'','activateage':'','agerequirementtoregisterfrominsidecountry':'','agerequirementtoregisterfromoutsidecountry':'' },
      { 'id': 14, 'class':'Third class','weekenddays':['Monday','Friday'],'schoolyearstartdate':'24/02/2021' , 'createddate': '(416) 4076124', 'schoolyearenddate': '30/09/2021', 'curriculum': 'Male', 'schoolyearname': 'Bosnia and Herzegovina','agedeterminationdate':'' ,'annualholidayname':'' , 'knownsubjectlist':'','subjectstatus':'','subjectstatusinfinaltotal':'','activateage':'','agerequirementtoregisterfrominsidecountry':'','agerequirementtoregisterfromoutsidecountry':'' },
      { 'id': 15, 'class':'Third class','weekenddays':['Monday','Friday'],'schoolyearstartdate':'24/02/2021' , 'createddate': '(262) 7945277', 'schoolyearenddate': '30/09/2021', 'curriculum': 'Female', 'schoolyearname': 'Bolivia','agedeterminationdate':'' ,'annualholidayname':'' , 'knownsubjectlist':'','subjectstatus':'','subjectstatusinfinaltotal':'','activateage':'','agerequirementtoregisterfrominsidecountry':'','agerequirementtoregisterfromoutsidecountry':'' },
      { 'id': 16, 'class':'Third class','weekenddays':['Monday','Friday'],'schoolyearstartdate':'24/02/2021' , 'createddate': '(501) 3984600', 'schoolyearenddate': '30/09/2021', 'curriculum': 'Female', 'schoolyearname': 'China','agedeterminationdate':'' ,'annualholidayname':'', 'knownsubjectlist':'','subjectstatus':'','subjectstatusinfinaltotal':'','activateage':'','agerequirementtoregisterfrominsidecountry':'','agerequirementtoregisterfromoutsidecountry':''  },
      { 'id': 17, 'class':'Third class','weekenddays':['Monday','Friday'],'schoolyearstartdate':'24/02/2021' , 'createddate': '(718) 4157883', 'schoolyearenddate': '30/09/2021', 'curriculum': 'Male', 'schoolyearname': 'Finland','agedeterminationdate':'' ,'annualholidayname':'' , 'knownsubjectlist':'','subjectstatus':'','subjectstatusinfinaltotal':'','activateage':'','agerequirementtoregisterfrominsidecountry':'','agerequirementtoregisterfromoutsidecountry':'' },
      { 'id': 18, 'class':'Third class','weekenddays':['Monday','Friday'],'schoolyearstartdate':'24/02/2021' , 'createddate': '(213) 5730967', 'schoolyearenddate': '30/09/2021', 'curriculum': 'Male', 'schoolyearname': 'Portugal','agedeterminationdate':'' ,'annualholidayname':'' , 'knownsubjectlist':'','subjectstatus':'','subjectstatusinfinaltotal':'','activateage':'','agerequirementtoregisterfrominsidecountry':'','agerequirementtoregisterfromoutsidecountry':'' },
      { 'id': 19, 'class':'Third class','weekenddays':['Monday','Friday'],'schoolyearstartdate':'24/02/2021' , 'createddate': '(349) 6453938', 'schoolyearenddate': '30/09/2021', 'curriculum': 'Female', 'schoolyearname': 'Madagascar','agedeterminationdate':'' ,'annualholidayname':'', 'knownsubjectlist':'','subjectstatus':'','subjectstatusinfinaltotal':'','activateage':'','agerequirementtoregisterfrominsidecountry':'','agerequirementtoregisterfromoutsidecountry':''  },
      { 'id': 20,'class':'Third class','weekenddays':['Monday','Friday'],'schoolyearstartdate':'24/02/2021' , 'createddate': '(474) 3068249', 'schoolyearenddate': '30/09/2021', 'curriculum': 'Female', 'schoolyearname': 'Greece','agedeterminationdate':'' ,'annualholidayname':'' , 'knownsubjectlist':'','subjectstatus':'','subjectstatusinfinaltotal':'','activateage':'','agerequirementtoregisterfrominsidecountry':'','agerequirementtoregisterfromoutsidecountry':'' }
    ];
    this.cities = [
      "2022",
       "Rome",
       "London",
       "Istanbul",
       "Paris"
  ];
   }
}
