import { Injectable } from '@angular/core';
import { Schoolyear } from 'src/app/core/Models/schoolyear';


@Injectable({
  providedIn: 'root'
})
export class SchoolYearService {
  cities: string[];
  SchoolYearList:Schoolyear[]=[];
  constructor() {

    this.SchoolYearList = [
      { 'id': 1, 'Class':'Third Class','WeekEndDays':['Monday','Friday'],'SchoolYearStartDate':'24/02/2021' , 'createdDate': '(815) 6180492', 'SchoolYearEndDate': '30/09/2021', 'curriculum': 'Female', 'SchoolYearName': 'Somalia','AgeDeterminationDate':'','AnnualHolidayName':'', 'KnownSubjectList':'','SubjectStatus':'','SubjectStatusInFinalTotal':'','ActivateAge':'','Agerequirementtoregisterfrominsidecountry':'','Agerequirementtoregisterfromoutsidecountry':'' },
      { 'id': 2, 'Class':'Third Class','WeekEndDays':['Monday','Friday'],'SchoolYearStartDate':'24/02/2021' , 'createdDate': '(507) 3119958', 'SchoolYearEndDate': '30/09/2021', 'curriculum': 'Male', 'SchoolYearName': 'United States','AgeDeterminationDate':'' ,'AnnualHolidayName':'', 'KnownSubjectList':'','SubjectStatus':'','SubjectStatusInFinalTotal':'','ActivateAge':'','Agerequirementtoregisterfrominsidecountry':'','Agerequirementtoregisterfromoutsidecountry':'' },
      { 'id': 3, 'Class':'Third Class','WeekEndDays':['Monday','Friday'],'SchoolYearStartDate':'24/02/2021' , 'createdDate': '(478) 7181722', 'SchoolYearEndDate': '30/09/2021', 'curriculum': 'Female', 'SchoolYearName': 'Russia','AgeDeterminationDate':'' ,'AnnualHolidayName':'' , 'KnownSubjectList':'','SubjectStatus':'','SubjectStatusInFinalTotal':'','ActivateAge':'','Agerequirementtoregisterfrominsidecountry':'','Agerequirementtoregisterfromoutsidecountry':'' },
      { 'id': 4, 'Class':'Third Class','WeekEndDays':['Monday','Friday'],'SchoolYearStartDate':'24/02/2021' , 'createdDate': '(698) 4411762', 'SchoolYearEndDate': '30/09/2021', 'curriculum': 'Female', 'SchoolYearName': 'China','AgeDeterminationDate':'' ,'AnnualHolidayName':'' , 'KnownSubjectList':'','SubjectStatus':'','SubjectStatusInFinalTotal':'','ActivateAge':'','Agerequirementtoregisterfrominsidecountry':'','Agerequirementtoregisterfromoutsidecountry':'' },
      { 'id': 5, 'Class':'Third Class','WeekEndDays':['Monday','Friday'],'SchoolYearStartDate':'24/02/2021' , 'createdDate': '(345) 6582965', 'SchoolYearEndDate': '30/09/2021', 'curriculum': 'Male', 'SchoolYearName': 'Mongolia','AgeDeterminationDate':'' ,'AnnualHolidayName':'' , 'KnownSubjectList':'','SubjectStatus':'','SubjectStatusInFinalTotal':'','ActivateAge':'','Agerequirementtoregisterfrominsidecountry':'','Agerequirementtoregisterfromoutsidecountry':'' },
      { 'id': 6, 'Class':'Third Class','WeekEndDays':['Monday','Friday'],'SchoolYearStartDate':'24/02/2021' , 'createdDate': '(659) 9557733', 'SchoolYearEndDate': '30/09/2021', 'curriculum': 'Male', 'SchoolYearName': 'Bhutan','AgeDeterminationDate':'' ,'AnnualHolidayName':'' , 'KnownSubjectList':'','SubjectStatus':'','SubjectStatusInFinalTotal':'','ActivateAge':'','Agerequirementtoregisterfrominsidecountry':'','Agerequirementtoregisterfromoutsidecountry':'' },
      { 'id': 7, 'Class':'Third Class','WeekEndDays':['Monday','Friday'],'SchoolYearStartDate':'24/02/2021' , 'createdDate': '(864) 2101861', 'SchoolYearEndDate': '30/09/2021', 'curriculum': 'Male', 'SchoolYearName': 'Peru','AgeDeterminationDate':'' ,'AnnualHolidayName':'', 'KnownSubjectList':'','SubjectStatus':'','SubjectStatusInFinalTotal':'','ActivateAge':'','Agerequirementtoregisterfrominsidecountry':'','Agerequirementtoregisterfromoutsidecountry':''  },
      { 'id': 8,'Class':'Third Class','WeekEndDays':['Monday','Friday'],'SchoolYearStartDate':'24/02/2021' , 'createdDate': '(165) 5814372', 'SchoolYearEndDate': '30/09/2021', 'curriculum': 'Male', 'SchoolYearName': 'Niger','AgeDeterminationDate':'' ,'AnnualHolidayName':'', 'KnownSubjectList':'','SubjectStatus':'','SubjectStatusInFinalTotal':'','ActivateAge':'','Agerequirementtoregisterfrominsidecountry':'','Agerequirementtoregisterfromoutsidecountry':''  },
      { 'id': 9, 'Class':'Third Class','WeekEndDays':['Monday','Friday'],'SchoolYearStartDate':'24/02/2021' , 'createdDate': '(428) 2282928', 'SchoolYearEndDate': '30/09/2021', 'curriculum': 'Female', 'SchoolYearName': 'Argentina','AgeDeterminationDate':'' ,'AnnualHolidayName':'' , 'KnownSubjectList':'','SubjectStatus':'','SubjectStatusInFinalTotal':'','ActivateAge':'','Agerequirementtoregisterfrominsidecountry':'','Agerequirementtoregisterfromoutsidecountry':'' },
      { 'id': 10, 'Class':'Third Class','WeekEndDays':['Monday','Friday'],'SchoolYearStartDate':'24/02/2021' , 'createdDate': '(673) 5170425', 'SchoolYearEndDate': '30/09/2021', 'curriculum': 'Female', 'SchoolYearName': 'Greece','AgeDeterminationDate':'' ,'AnnualHolidayName':'', 'KnownSubjectList':'','SubjectStatus':'','SubjectStatusInFinalTotal':'','ActivateAge':'','Agerequirementtoregisterfrominsidecountry':'','Agerequirementtoregisterfromoutsidecountry':''  },
      { 'id': 11, 'Class':'Third Class','WeekEndDays':['Monday','Friday'],'SchoolYearStartDate':'24/02/2021' , 'createdDate': '(978) 8885907', 'SchoolYearEndDate': '30/09/2021', 'curriculum': 'Female', 'SchoolYearName': 'Indonesia','AgeDeterminationDate':'' ,'AnnualHolidayName':'' , 'KnownSubjectList':'','SubjectStatus':'','SubjectStatusInFinalTotal':'','ActivateAge':'','Agerequirementtoregisterfrominsidecountry':'','Agerequirementtoregisterfromoutsidecountry':'' },
      { 'id': 12, 'Class':'Third Class','WeekEndDays':['Monday','Friday'],'SchoolYearStartDate':'24/02/2021' , 'createdDate': '(956) 9360112', 'SchoolYearEndDate': '30/09/2021', 'curriculum': 'Female', 'SchoolYearName': 'Finland','AgeDeterminationDate':'' ,'AnnualHolidayName':'', 'KnownSubjectList':'','SubjectStatus':'','SubjectStatusInFinalTotal':'','ActivateAge':'','Agerequirementtoregisterfrominsidecountry':'','Agerequirementtoregisterfromoutsidecountry':''  },
      { 'id': 13, 'Class':'Third Class','WeekEndDays':['Monday','Friday'],'SchoolYearStartDate':'24/02/2021' , 'createdDate': '(240) 7150720', 'SchoolYearEndDate': '30/09/2021', 'curriculum': 'Female', 'SchoolYearName': 'Philippines' ,'AgeDeterminationDate':'' ,'AnnualHolidayName':'', 'KnownSubjectList':'','SubjectStatus':'','SubjectStatusInFinalTotal':'','ActivateAge':'','Agerequirementtoregisterfrominsidecountry':'','Agerequirementtoregisterfromoutsidecountry':'' },
      { 'id': 14, 'Class':'Third Class','WeekEndDays':['Monday','Friday'],'SchoolYearStartDate':'24/02/2021' , 'createdDate': '(416) 4076124', 'SchoolYearEndDate': '30/09/2021', 'curriculum': 'Male', 'SchoolYearName': 'Bosnia and Herzegovina','AgeDeterminationDate':'' ,'AnnualHolidayName':'' , 'KnownSubjectList':'','SubjectStatus':'','SubjectStatusInFinalTotal':'','ActivateAge':'','Agerequirementtoregisterfrominsidecountry':'','Agerequirementtoregisterfromoutsidecountry':'' },
      { 'id': 15, 'Class':'Third Class','WeekEndDays':['Monday','Friday'],'SchoolYearStartDate':'24/02/2021' , 'createdDate': '(262) 7945277', 'SchoolYearEndDate': '30/09/2021', 'curriculum': 'Female', 'SchoolYearName': 'Bolivia','AgeDeterminationDate':'' ,'AnnualHolidayName':'' , 'KnownSubjectList':'','SubjectStatus':'','SubjectStatusInFinalTotal':'','ActivateAge':'','Agerequirementtoregisterfrominsidecountry':'','Agerequirementtoregisterfromoutsidecountry':'' },
      { 'id': 16, 'Class':'Third Class','WeekEndDays':['Monday','Friday'],'SchoolYearStartDate':'24/02/2021' , 'createdDate': '(501) 3984600', 'SchoolYearEndDate': '30/09/2021', 'curriculum': 'Female', 'SchoolYearName': 'China','AgeDeterminationDate':'' ,'AnnualHolidayName':'', 'KnownSubjectList':'','SubjectStatus':'','SubjectStatusInFinalTotal':'','ActivateAge':'','Agerequirementtoregisterfrominsidecountry':'','Agerequirementtoregisterfromoutsidecountry':''  },
      { 'id': 17, 'Class':'Third Class','WeekEndDays':['Monday','Friday'],'SchoolYearStartDate':'24/02/2021' , 'createdDate': '(718) 4157883', 'SchoolYearEndDate': '30/09/2021', 'curriculum': 'Male', 'SchoolYearName': 'Finland','AgeDeterminationDate':'' ,'AnnualHolidayName':'' , 'KnownSubjectList':'','SubjectStatus':'','SubjectStatusInFinalTotal':'','ActivateAge':'','Agerequirementtoregisterfrominsidecountry':'','Agerequirementtoregisterfromoutsidecountry':'' },
      { 'id': 18, 'Class':'Third Class','WeekEndDays':['Monday','Friday'],'SchoolYearStartDate':'24/02/2021' , 'createdDate': '(213) 5730967', 'SchoolYearEndDate': '30/09/2021', 'curriculum': 'Male', 'SchoolYearName': 'Portugal','AgeDeterminationDate':'' ,'AnnualHolidayName':'' , 'KnownSubjectList':'','SubjectStatus':'','SubjectStatusInFinalTotal':'','ActivateAge':'','Agerequirementtoregisterfrominsidecountry':'','Agerequirementtoregisterfromoutsidecountry':'' },
      { 'id': 19, 'Class':'Third Class','WeekEndDays':['Monday','Friday'],'SchoolYearStartDate':'24/02/2021' , 'createdDate': '(349) 6453938', 'SchoolYearEndDate': '30/09/2021', 'curriculum': 'Female', 'SchoolYearName': 'Madagascar','AgeDeterminationDate':'' ,'AnnualHolidayName':'', 'KnownSubjectList':'','SubjectStatus':'','SubjectStatusInFinalTotal':'','ActivateAge':'','Agerequirementtoregisterfrominsidecountry':'','Agerequirementtoregisterfromoutsidecountry':''  },
      { 'id': 20,'Class':'Third Class','WeekEndDays':['Monday','Friday'],'SchoolYearStartDate':'24/02/2021' , 'createdDate': '(474) 3068249', 'SchoolYearEndDate': '30/09/2021', 'curriculum': 'Female', 'SchoolYearName': 'Greece','AgeDeterminationDate':'' ,'AnnualHolidayName':'' , 'KnownSubjectList':'','SubjectStatus':'','SubjectStatusInFinalTotal':'','ActivateAge':'','Agerequirementtoregisterfrominsidecountry':'','Agerequirementtoregisterfromoutsidecountry':'' }
    ];
    this.cities = [
      "2022",
       "Rome",
       "London",
       "Istanbul",
       "Paris"
  ];
   }
}
