export enum IndexesEnum{


    TheMainReasonsForRejectionOfTheApplicationForRegistration = 'TheMainReasonsForRejectionOfTheApplicationForRegistration',
    ReasonsForRefusingToRemoveAStudentFromASchool = 'ReasonsForRefusingToRemoveAStudentFromASchool',
    TheMainReasonsForStudentDeletion = 'TheMainReasonsForStudentDeletion',
    ReasonsForWithdrawingTheStudentFromTheCurrentSchool = 'ReasonsForWithdrawingTheStudentFromTheCurrentSchool',
    TheReasonForRejectingTheWithdrawalRequest = 'TheReasonForRejectingTheWithdrawalRequest',
    TheTypeOfTalentOfTheStudent = 'TheTypeOfTalentOfTheStudent',
    // ReasonsForRepeatingASpecificCourseOrSubject = 'ReasonsForRepeatingASpecificCourseOrSubject',
    DiplomaType = 'DiplomaType',
    TtypeOfCommunicationMessage = 'TtypeOfCommunicationMessage',
    TypesOfFileAttachmentsForSchoolStaff = 'TypesOfFileAttachmentsForSchoolStaff',
    TheTypeOfFileAttachmentForTheParent = 'TheTypeOfFileAttachmentForTheParent',
    CitiesOfSharjah = 'CitiesOfSharjah',
    CitiesOfTheCentralRegion = 'CitiesOfTheCentralRegion',
    EasternProvinceCities = 'EasternProvinceCities',
    TypesOfGradeImprovement = 'TypesOfGradeImprovement',
    NationalityCategory = 'NationalityCategory',
    SpecialEducation = 'SpecialEducation',
    Language ='Language',
    ReasonsForIssuingBoardCertificate ="ReasonsForIssuingBoardCertificate",
    TheReasonForLackOfIdentification = 'TheReasonForLackOfIdentification',
    TheReasonForAbsent ="TheReasonForAbsent",
    TheReasonForRegradingRequest ="TheReasonForRegradingRequest",
    TheReasonForWithdrawalRequest ="TheReasonForWithdrawalRequest",
    ModifyStudentResult ="ModifyStudentResult",
    TheReasonForRejectRegradingRequest ="TheReasonForRejectRegradingRequest ",
    reEnrollmentTypes=27
}
