export enum IndexesEnum{
    NationalityCategory = 'NationalityCategory',
    SpecialEducation = 'SpecialEducation',
    languages ='languages',
    TheMainReasonsForRejectionOfTheApplicationForRegistration = 'TheMainReasonsForRejectionOfTheApplicationForRegistration',
    ReasonsForRefusingToRemoveAStudentFromASchool = 'ReasonsForRefusingToRemoveAStudentFromASchool',
    ReasonsForRefusingARequestToDelete = 'ReasonsForRefusingARequestToDelete',
    ReasonsForWithdrawingTheStudentFromTheCurrentSchool = 'ReasonsForWithdrawingTheStudentFromTheCurrentSchool',
    TheReasonForRejectingTheWithdrawalRequest = 'TheReasonForRejectingTheWithdrawalRequest',
    TheTypeOfTalentOfTheStudent = 'TheTypeOfTalentOfTheStudent',
    ReasonsForRepeatingASpecificCourseOrSubject = 'ReasonsForRepeatingASpecificCourseOrSubject',
    DiplomaType = 'DiplomaType',
    TtypeOfCommunicationMessage = 'TtypeOfCommunicationMessage',
    TypesOfFileAttachmentsForSchoolStaff = 'TypesOfFileAttachmentsForSchoolStaff',
    TheTypeOfFileAttachmentForTheParent = 'TheTypeOfFileAttachmentForTheParent',
    CitiesOfSharjah = 'CitiesOfSharjah',
    CitiesOfTheCentralRegion = 'CitiesOfTheCentralRegion',
    EasternProvinceCities = 'EasternProvinceCities',
    TypesOfGradeImprovement = 'TypesOfGradeImprovement',
    ExcusedAbsences = 'ExcusedAbsences',

}